---
driver_plugin: docker

driver_config:
  use_sudo: false
  privileged: true
  socket: <%= ENV['DOCKER_HOST'] || 'unix:///var/run/docker.sock' %>
  volume:
  - <%= ENV['PWD'] %>:/home/kitchen/project

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[conjurops-jenkins-slave]
    attributes:
