driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  ssh_key: <%= ENV['SSH_PRIVATE_KEY_PATH'] %>
  region: us-east-1
  flavor_id: m3.medium

transport:
  forward_agent: true

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: <%= ENV['AWS_BASE_AMI'] %> # comes from secrets.ci.yml
      username: ubuntu

suites:
  - name: slave
    run_list:
      - recipe[conjurops-jenkins-slave::slave]
