---
driver_plugin: docker

driver_config:
  socket: <%= ENV['DOCKER_HOST'] || 'unix:///var/run/docker.sock' %>
  volume:
  - <%= ENV['NETRC_PATH'] %>:/home/kitchen/project
  forward:
  - 8080:8080

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04

suites:
  - name: master
    run_list:
      - recipe[conjurops-jenkins::master]
    attributes:
