driver: 
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEY_NAME'] %>
  ssh_key: private_key
  region: us-east-1
  flavor_id: m3.medium

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: <%= ENV['AWS_BASE_AMI'] %>
      username: ubuntu
