driver:
  name: vagrant

transport:
  forward_agent: true
  
driver_config:
  ssh:
    forward_agent: true
  
provisioner:
  name: chef_zero

platforms:
- name: phusion/ubuntu-14.04-amd64

suites:
  - name: default
    run_list:
      - recipe[conjurops-jenkins-slave]
    attributes:
