---
driver_plugin: docker

driver_config:
  socket: <%= ENV['DOCKER_HOST'] || 'unix:///var/run/docker.sock' %>
  volume:
  - <%= ENV['NETRC_PATH'] %>:/home/kitchen/project

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04

suites:
  - name: master
    forward:
    - 8080:8080
    run_list:
      - recipe[conjurops-jenkins::master]
    attributes:

  - name: slave
    run_list:
      - recipe[conjurops-jenkins::slave]
    attributes:
