driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  instance_type: m3.medium

transport:
  forward_agent: true
  ssh_key: <%= ENV['SSH_PRIVATE_KEY_PATH'] %>
  username: ubuntu

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: <%= ENV['AWS_BASE_AMI'] %> # comes from secrets.ci.yml

suites:
  - name: slave
    run_list:
      - recipe[conjurops-jenkins-slave::slave]
