Vagrant.configure('2') do |config|
  config.vm.box = 'dummy'

  config.vm.provider :aws do |aws, override|
    override.ssh.username = 'ubuntu'

    # ubuntu 14.04 64bit
    aws.region = 'us-east-1'
    aws.ami = 'ami-92f569fa'
    aws.instance_type = 'm1.medium'

    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
  end
end
